/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import crud.crud;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
    crud mycode;

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        mycode= new crud();
        mycode.tampilDataPengacara(tabelPengacara, "SELECT*FROM pengacara");
        mycode.tampilDataKlien(tabelKlien, "SELECT*FROM klien");
        mycode.tampilDataPerkara(tabelPerkara, "SELECT*FROM perkara");
        mycode.tampilDataKategoriPerkara(tabelKategoriPerkara, "SELECT*FROM kategori_perkara");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlKlien = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtTempatLahir = new javax.swing.JTextField();
        txtNamaKlien = new javax.swing.JTextField();
        txtTanggalLahir = new javax.swing.JTextField();
        btnHpsKlien = new javax.swing.JButton();
        btnSmpnKlien = new javax.swing.JButton();
        btnUbhKlien = new javax.swing.JButton();
        txtCariKlien = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelKlien = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        txtIdKlien = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtKtp = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtAlamatKlien = new javax.swing.JTextField();
        txtPekerjaan = new javax.swing.JTextField();
        txtTeleponKlien = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtJenisKelamin = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtEmailKlien = new javax.swing.JTextField();
        btnCetakKlien = new javax.swing.JButton();
        pnlPengacara = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtAlamatPengacara = new javax.swing.JTextField();
        txtNamaPengacara = new javax.swing.JTextField();
        txtTeleponPengacara = new javax.swing.JTextField();
        btnHpsPengacara = new javax.swing.JButton();
        btnSmpnPengacara = new javax.swing.JButton();
        btnUbhPengacara = new javax.swing.JButton();
        txtCariPengacara = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelPengacara = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        txtIdPengacara = new javax.swing.JTextField();
        txtInstansi = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        btnCetakPengacara = new javax.swing.JButton();
        pnlKategoriPerkara = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtJenisPerkara_Kat = new javax.swing.JTextField();
        txtNamaPerkara = new javax.swing.JTextField();
        txtDeskripsiPerkara = new javax.swing.JTextField();
        btnHpsKat = new javax.swing.JButton();
        btnSmpnKat = new javax.swing.JButton();
        btnUbhKat = new javax.swing.JButton();
        txtCariKategoriPerkara = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelKategoriPerkara = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        txtIdKategori = new javax.swing.JTextField();
        btnCetakKat = new javax.swing.JButton();
        pnlPerkara = new javax.swing.JPanel();
        btnHpsPerkara = new javax.swing.JButton();
        btnSmpnPerkara = new javax.swing.JButton();
        btnUbhPerkara = new javax.swing.JButton();
        txtCariPerkara = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelPerkara = new javax.swing.JTable();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtNoPerkara = new javax.swing.JTextField();
        txtJenisPerkara_Per = new javax.swing.JTextField();
        txtKategoriId = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        txtIdPerkara = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txtTglSelesai = new javax.swing.JTextField();
        txtTglMulai = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        txtNamaTerdakwa = new javax.swing.JTextField();
        txtKlienId = new javax.swing.JTextField();
        txtPengacaraId = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        txtStatusPerkara = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        txtDokumen = new javax.swing.JTextField();
        txtKeteranganPerkara = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        txtSuratKuasa = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        btnCetakPerkara = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnKlien = new javax.swing.JButton();
        btnPengacara = new javax.swing.JButton();
        btnKategoriPerkara = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnPerkara = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        Content.add(pnlHome, "card6");

        pnlKlien.setBackground(new java.awt.Color(51, 51, 255));
        pnlKlien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Tanggal Lahir");
        pnlKlien.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 132, -1));

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Tempat Lahir");
        pnlKlien.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 130, -1));

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Nama");
        pnlKlien.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtTempatLahir.setBackground(new java.awt.Color(255, 255, 255));
        txtTempatLahir.setForeground(new java.awt.Color(0, 0, 0));
        pnlKlien.add(txtTempatLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtNamaKlien.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaKlien.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaKlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaKlienActionPerformed(evt);
            }
        });
        pnlKlien.add(txtNamaKlien, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtTanggalLahir.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggalLahir.setForeground(new java.awt.Color(0, 0, 0));
        pnlKlien.add(txtTanggalLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsKlien.setText("HAPUS");
        btnHpsKlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsKlienActionPerformed(evt);
            }
        });
        pnlKlien.add(btnHpsKlien, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 90, 30));

        btnSmpnKlien.setText("SIMPAN");
        btnSmpnKlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnKlienActionPerformed(evt);
            }
        });
        pnlKlien.add(btnSmpnKlien, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 90, 30));

        btnUbhKlien.setText("UBAH");
        btnUbhKlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhKlienActionPerformed(evt);
            }
        });
        pnlKlien.add(btnUbhKlien, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 90, 30));

        txtCariKlien.setBackground(new java.awt.Color(255, 255, 255));
        txtCariKlien.setForeground(new java.awt.Color(0, 0, 0));
        txtCariKlien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKlienKeyReleased(evt);
            }
        });
        pnlKlien.add(txtCariKlien, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 370, -1));

        tabelKlien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKlien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKlienMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelKlien);

        pnlKlien.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 760, 155));

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("ID Klien");
        pnlKlien.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdKlien.setBackground(new java.awt.Color(255, 255, 255));
        txtIdKlien.setForeground(new java.awt.Color(0, 0, 0));
        pnlKlien.add(txtIdKlien, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        jLabel22.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("KTP");
        pnlKlien.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 132, -1));

        txtKtp.setBackground(new java.awt.Color(255, 255, 255));
        txtKtp.setForeground(new java.awt.Color(0, 0, 0));
        pnlKlien.add(txtKtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Telepon");
        pnlKlien.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 132, -1));

        jLabel41.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Alamat");
        pnlKlien.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 130, -1));

        jLabel42.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Pekerjaan");
        pnlKlien.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        txtAlamatKlien.setBackground(new java.awt.Color(255, 255, 255));
        txtAlamatKlien.setForeground(new java.awt.Color(0, 0, 0));
        pnlKlien.add(txtAlamatKlien, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 220, -1));

        txtPekerjaan.setBackground(new java.awt.Color(255, 255, 255));
        txtPekerjaan.setForeground(new java.awt.Color(0, 0, 0));
        pnlKlien.add(txtPekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 220, -1));

        txtTeleponKlien.setBackground(new java.awt.Color(255, 255, 255));
        txtTeleponKlien.setForeground(new java.awt.Color(0, 0, 0));
        pnlKlien.add(txtTeleponKlien, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 220, -1));

        jLabel43.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Jenis Kelamin");
        pnlKlien.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        txtJenisKelamin.setBackground(new java.awt.Color(255, 255, 255));
        txtJenisKelamin.setForeground(new java.awt.Color(0, 0, 0));
        pnlKlien.add(txtJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 220, -1));

        jLabel44.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Email");
        pnlKlien.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 132, -1));

        txtEmailKlien.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailKlien.setForeground(new java.awt.Color(0, 0, 0));
        pnlKlien.add(txtEmailKlien, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 220, -1));

        btnCetakKlien.setText("CETAK");
        btnCetakKlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakKlienActionPerformed(evt);
            }
        });
        pnlKlien.add(btnCetakKlien, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 90, 30));

        Content.add(pnlKlien, "card4");

        pnlPengacara.setBackground(new java.awt.Color(51, 51, 255));
        pnlPengacara.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Telepon");
        pnlPengacara.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Alamat");
        pnlPengacara.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Nama ");
        pnlPengacara.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtAlamatPengacara.setBackground(new java.awt.Color(255, 255, 255));
        txtAlamatPengacara.setForeground(new java.awt.Color(0, 0, 0));
        pnlPengacara.add(txtAlamatPengacara, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtNamaPengacara.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaPengacara.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaPengacara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPengacaraActionPerformed(evt);
            }
        });
        pnlPengacara.add(txtNamaPengacara, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtTeleponPengacara.setBackground(new java.awt.Color(255, 255, 255));
        txtTeleponPengacara.setForeground(new java.awt.Color(0, 0, 0));
        pnlPengacara.add(txtTeleponPengacara, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsPengacara.setText("HAPUS");
        btnHpsPengacara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsPengacaraActionPerformed(evt);
            }
        });
        pnlPengacara.add(btnHpsPengacara, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 90, -1));

        btnSmpnPengacara.setText("SIMPAN");
        btnSmpnPengacara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnPengacaraActionPerformed(evt);
            }
        });
        pnlPengacara.add(btnSmpnPengacara, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 90, -1));

        btnUbhPengacara.setText("UBAH");
        btnUbhPengacara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhPengacaraActionPerformed(evt);
            }
        });
        pnlPengacara.add(btnUbhPengacara, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 90, -1));

        txtCariPengacara.setBackground(new java.awt.Color(255, 255, 255));
        txtCariPengacara.setForeground(new java.awt.Color(0, 0, 0));
        txtCariPengacara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPengacaraKeyReleased(evt);
            }
        });
        pnlPengacara.add(txtCariPengacara, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 370, -1));

        tabelPengacara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPengacara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPengacaraMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelPengacara);

        pnlPengacara.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 480, 155));

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("ID Pengacara");
        pnlPengacara.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdPengacara.setBackground(new java.awt.Color(255, 255, 255));
        txtIdPengacara.setForeground(new java.awt.Color(0, 0, 0));
        txtIdPengacara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPengacaraActionPerformed(evt);
            }
        });
        pnlPengacara.add(txtIdPengacara, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        txtInstansi.setBackground(new java.awt.Color(255, 255, 255));
        txtInstansi.setForeground(new java.awt.Color(0, 0, 0));
        pnlPengacara.add(txtInstansi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Instansi");
        pnlPengacara.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 90, -1));

        btnCetakPengacara.setText("CETAK");
        btnCetakPengacara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakPengacaraActionPerformed(evt);
            }
        });
        pnlPengacara.add(btnCetakPengacara, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 90, -1));

        Content.add(pnlPengacara, "card3");

        pnlKategoriPerkara.setBackground(new java.awt.Color(51, 51, 255));
        pnlKategoriPerkara.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Deskripsi Perkara");
        pnlKategoriPerkara.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel31.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Jenis Perkara");
        pnlKategoriPerkara.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel32.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Nama Perkara");
        pnlKategoriPerkara.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtJenisPerkara_Kat.setBackground(new java.awt.Color(255, 255, 255));
        txtJenisPerkara_Kat.setForeground(new java.awt.Color(0, 0, 0));
        pnlKategoriPerkara.add(txtJenisPerkara_Kat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 220, -1));

        txtNamaPerkara.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaPerkara.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaPerkara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPerkaraActionPerformed(evt);
            }
        });
        pnlKategoriPerkara.add(txtNamaPerkara, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 220, -1));

        txtDeskripsiPerkara.setBackground(new java.awt.Color(255, 255, 255));
        txtDeskripsiPerkara.setForeground(new java.awt.Color(0, 0, 0));
        pnlKategoriPerkara.add(txtDeskripsiPerkara, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 220, -1));

        btnHpsKat.setText("HAPUS");
        btnHpsKat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsKatActionPerformed(evt);
            }
        });
        pnlKategoriPerkara.add(btnHpsKat, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 90, -1));

        btnSmpnKat.setText("SIMPAN");
        btnSmpnKat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnKatActionPerformed(evt);
            }
        });
        pnlKategoriPerkara.add(btnSmpnKat, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 90, -1));

        btnUbhKat.setText("UBAH");
        btnUbhKat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhKatActionPerformed(evt);
            }
        });
        pnlKategoriPerkara.add(btnUbhKat, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 90, -1));

        txtCariKategoriPerkara.setBackground(new java.awt.Color(255, 255, 255));
        txtCariKategoriPerkara.setForeground(new java.awt.Color(0, 0, 0));
        txtCariKategoriPerkara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKategoriPerkaraKeyReleased(evt);
            }
        });
        pnlKategoriPerkara.add(txtCariKategoriPerkara, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 390, -1));

        tabelKategoriPerkara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKategoriPerkara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKategoriPerkaraMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tabelKategoriPerkara);

        pnlKategoriPerkara.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 500, 155));

        jLabel33.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("ID Kategori");
        pnlKategoriPerkara.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdKategori.setBackground(new java.awt.Color(255, 255, 255));
        txtIdKategori.setForeground(new java.awt.Color(0, 0, 0));
        txtIdKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdKategoriActionPerformed(evt);
            }
        });
        pnlKategoriPerkara.add(txtIdKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 220, -1));

        btnCetakKat.setText("CETAK");
        btnCetakKat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakKatActionPerformed(evt);
            }
        });
        pnlKategoriPerkara.add(btnCetakKat, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 90, -1));

        Content.add(pnlKategoriPerkara, "card5");

        pnlPerkara.setBackground(new java.awt.Color(51, 51, 255));
        pnlPerkara.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHpsPerkara.setText("HAPUS");
        btnHpsPerkara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsPerkaraActionPerformed(evt);
            }
        });
        pnlPerkara.add(btnHpsPerkara, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 90, 30));

        btnSmpnPerkara.setText("SIMPAN");
        btnSmpnPerkara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnPerkaraActionPerformed(evt);
            }
        });
        pnlPerkara.add(btnSmpnPerkara, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 90, 30));

        btnUbhPerkara.setText("UBAH");
        btnUbhPerkara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhPerkaraActionPerformed(evt);
            }
        });
        pnlPerkara.add(btnUbhPerkara, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 90, 30));

        txtCariPerkara.setBackground(new java.awt.Color(255, 255, 255));
        txtCariPerkara.setForeground(new java.awt.Color(0, 0, 0));
        txtCariPerkara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPerkaraKeyReleased(evt);
            }
        });
        pnlPerkara.add(txtCariPerkara, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 370, -1));

        tabelPerkara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPerkara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPerkaraMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tabelPerkara);

        pnlPerkara.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 770, 170));

        jLabel45.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("ID Kategori");
        pnlPerkara.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        jLabel46.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("No Perkara");
        pnlPerkara.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel47.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Jenis Perkara");
        pnlPerkara.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtNoPerkara.setBackground(new java.awt.Color(255, 255, 255));
        txtNoPerkara.setForeground(new java.awt.Color(0, 0, 0));
        pnlPerkara.add(txtNoPerkara, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtJenisPerkara_Per.setBackground(new java.awt.Color(255, 255, 255));
        txtJenisPerkara_Per.setForeground(new java.awt.Color(0, 0, 0));
        pnlPerkara.add(txtJenisPerkara_Per, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtKategoriId.setBackground(new java.awt.Color(255, 255, 255));
        txtKategoriId.setForeground(new java.awt.Color(0, 0, 0));
        pnlPerkara.add(txtKategoriId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        jLabel48.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("ID Perkara ");
        pnlPerkara.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdPerkara.setBackground(new java.awt.Color(255, 255, 255));
        txtIdPerkara.setForeground(new java.awt.Color(0, 0, 0));
        pnlPerkara.add(txtIdPerkara, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        jLabel49.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Tanggal Selesai");
        pnlPerkara.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 140, -1));

        txtTglSelesai.setBackground(new java.awt.Color(255, 255, 255));
        txtTglSelesai.setForeground(new java.awt.Color(0, 0, 0));
        pnlPerkara.add(txtTglSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 220, -1));

        txtTglMulai.setBackground(new java.awt.Color(255, 255, 255));
        txtTglMulai.setForeground(new java.awt.Color(0, 0, 0));
        pnlPerkara.add(txtTglMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        jLabel50.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Tanggal Mulai");
        pnlPerkara.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel57.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 0));
        jLabel57.setText("ID Pengacara");
        pnlPerkara.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 120, -1));

        jLabel58.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 0, 0));
        jLabel58.setText("Nama Terdakwa");
        pnlPerkara.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 140, -1));

        jLabel59.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 0, 0));
        jLabel59.setText("ID Klien");
        pnlPerkara.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        txtNamaTerdakwa.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaTerdakwa.setForeground(new java.awt.Color(0, 0, 0));
        pnlPerkara.add(txtNamaTerdakwa, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 220, -1));

        txtKlienId.setBackground(new java.awt.Color(255, 255, 255));
        txtKlienId.setForeground(new java.awt.Color(0, 0, 0));
        pnlPerkara.add(txtKlienId, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 220, -1));

        txtPengacaraId.setBackground(new java.awt.Color(255, 255, 255));
        txtPengacaraId.setForeground(new java.awt.Color(0, 0, 0));
        pnlPerkara.add(txtPengacaraId, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 220, -1));

        jLabel60.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 0, 0));
        jLabel60.setText("Status ");
        pnlPerkara.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 140, -1));

        txtStatusPerkara.setBackground(new java.awt.Color(255, 255, 255));
        txtStatusPerkara.setForeground(new java.awt.Color(0, 0, 0));
        pnlPerkara.add(txtStatusPerkara, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 220, -1));

        jLabel61.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 0, 0));
        jLabel61.setText("Dokumen");
        pnlPerkara.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 110, -1));

        txtDokumen.setBackground(new java.awt.Color(255, 255, 255));
        txtDokumen.setForeground(new java.awt.Color(0, 0, 0));
        pnlPerkara.add(txtDokumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 220, -1));

        txtKeteranganPerkara.setBackground(new java.awt.Color(255, 255, 255));
        txtKeteranganPerkara.setForeground(new java.awt.Color(0, 0, 0));
        pnlPerkara.add(txtKeteranganPerkara, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 220, -1));

        jLabel62.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 0, 0));
        jLabel62.setText("Keterangan ");
        pnlPerkara.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        txtSuratKuasa.setBackground(new java.awt.Color(255, 255, 255));
        txtSuratKuasa.setForeground(new java.awt.Color(0, 0, 0));
        pnlPerkara.add(txtSuratKuasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 220, -1));

        jLabel63.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 0, 0));
        jLabel63.setText("Surat Kuasa");
        pnlPerkara.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 110, -1));

        btnCetakPerkara.setText("CETAK");
        btnCetakPerkara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakPerkaraActionPerformed(evt);
            }
        });
        pnlPerkara.add(btnCetakPerkara, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 90, 30));

        Content.add(pnlPerkara, "card5");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM INFORMASI MANAJEMEN PERKARA");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(0, 0, 153));
        Menu.setForeground(new java.awt.Color(255, 255, 255));

        btnKlien.setBackground(new java.awt.Color(255, 255, 255));
        btnKlien.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnKlien.setForeground(new java.awt.Color(0, 0, 0));
        btnKlien.setText("KLIEN");
        btnKlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlienActionPerformed(evt);
            }
        });

        btnPengacara.setBackground(new java.awt.Color(255, 255, 255));
        btnPengacara.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnPengacara.setForeground(new java.awt.Color(0, 0, 0));
        btnPengacara.setText("PENGACARA");
        btnPengacara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengacaraActionPerformed(evt);
            }
        });

        btnKategoriPerkara.setBackground(new java.awt.Color(255, 255, 255));
        btnKategoriPerkara.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnKategoriPerkara.setForeground(new java.awt.Color(0, 0, 0));
        btnKategoriPerkara.setText("KATEGORI PERKARA");
        btnKategoriPerkara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKategoriPerkaraActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnPerkara.setBackground(new java.awt.Color(255, 255, 255));
        btnPerkara.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnPerkara.setForeground(new java.awt.Color(0, 0, 0));
        btnPerkara.setText("PERKARA");
        btnPerkara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerkaraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnPengacara)
            .addComponent(btnKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnKategoriPerkara, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(btnPerkara, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnKategoriPerkara, btnKlien, btnPengacara, btnPerkara});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPengacara)
                .addGap(18, 18, 18)
                .addComponent(btnKategoriPerkara)
                .addGap(18, 18, 18)
                .addComponent(btnPerkara)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnKategoriPerkara, btnKlien, btnPengacara, btnPerkara});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnKlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlienActionPerformed
        Content.removeAll(); 
        Content.add(pnlKlien);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnKlienActionPerformed

    private void btnPengacaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengacaraActionPerformed
        Content.removeAll(); 
        Content.add(pnlPengacara);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnPengacaraActionPerformed

    private void btnKategoriPerkaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategoriPerkaraActionPerformed
        Content.removeAll(); 
        Content.add(pnlKategoriPerkara);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnKategoriPerkaraActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnPerkaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerkaraActionPerformed
        Content.removeAll(); 
        Content.add(pnlPerkara);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnPerkaraActionPerformed

    private void txtCariKlienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKlienKeyReleased
        String c = txtCariKlien.getText();
        // Pola 01 (Tidak Aman) sesuai contoh Anda
        String cari = "SELECT*FROM klien WHERE id LIKE '%"+c+"%'"+
                      "OR nama_klien LIKE '%"+c+"%' OR tempat_lahir LIKE '%"+c+"%'"+
                      "OR ktp LIKE '%"+c+"%' OR pekerjaan LIKE '%"+c+"%'"+
                      "OR alamat LIKE '%"+c+"%' OR telepon LIKE '%"+c+"%'";
        mycode.tampilDataKlien(tabelKlien, cari);
    }//GEN-LAST:event_txtCariKlienKeyReleased

    private void btnUbhKlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhKlienActionPerformed
        try {
            mycode.ubahKlien(txtIdKlien.getText(), txtNamaKlien.getText(),
                             txtTempatLahir.getText(), txtTanggalLahir.getText(),
                             txtKtp.getText(), txtJenisKelamin.getText(),
                             txtPekerjaan.getText(), txtAlamatKlien.getText(),
                             txtTeleponKlien.getText(), txtEmailKlien.getText());

            // Refresh tabel
            mycode.tampilDataKlien(tabelKlien, "SELECT*FROM klien");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhKlienActionPerformed

    private void btnSmpnKlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnKlienActionPerformed
        try {
            if(txtIdKlien.getText().isEmpty()){ // Asumsi nama: txtIdKlien
                JOptionPane.showMessageDialog(null, "ID Belum Diisi");
                txtIdKlien.requestFocus();
            } else if(txtNamaKlien.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Klien Belum Diisi");
                txtNamaKlien.requestFocus();
            } else if(txtTempatLahir.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tempat Lahir Belum Diisi");
                txtTempatLahir.requestFocus();
            } else if(txtTanggalLahir.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tanggal Lahir Belum Diisi");
                txtTanggalLahir.requestFocus();
            } else if(txtKtp.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "KTP Belum Diisi");
                txtKtp.requestFocus();
            } else if(txtJenisKelamin.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Jenis Kelamin Belum Diisi");
                txtJenisKelamin.requestFocus();
            } else if(txtPekerjaan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Pekerjaan Belum Diisi");
                txtPekerjaan.requestFocus();
            } else if(txtAlamatKlien.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "Alamat Belum Diisi");
                txtAlamatKlien.requestFocus();
            } else if(txtTeleponKlien.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "Telepon Belum Diisi");
                txtTeleponKlien.requestFocus();
            } else if(txtEmailKlien.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "Email Belum Diisi");
                txtEmailKlien.requestFocus();
            } else {
                // Sesuai pola, memanggil simpan02 untuk keamanan dan cek duplikasi
                mycode.simpanKlien02(txtIdKlien.getText(), txtNamaKlien.getText(),
                                     txtTempatLahir.getText(), txtTanggalLahir.getText(),
                                     txtKtp.getText(), txtJenisKelamin.getText(),
                                     txtPekerjaan.getText(), txtAlamatKlien.getText(),
                                     txtTeleponKlien.getText(), txtEmailKlien.getText());

                // Refresh tabel
                mycode.tampilDataKlien(tabelKlien, "SELECT*FROM klien");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtNamaKlien.setText(mycode.CEK_NAMA_KLIEN);
                    txtTempatLahir.setText(mycode.CEK_TEMPAT_LAHIR);
                    txtTanggalLahir.setText(mycode.CEK_TANGGAL_LAHIR);
                    txtKtp.setText(mycode.CEK_KTP);
                    txtJenisKelamin.setText(mycode.CEK_JENIS_KELAMIN);
                    txtPekerjaan.setText(mycode.CEK_PEKERJAAN);
                    txtAlamatKlien.setText(mycode.CEK_ALAMAT_KLIEN);
                    txtTeleponKlien.setText(mycode.CEK_TELEPON_KLIEN);
                    txtEmailKlien.setText(mycode.CEK_EMAIL_KLIEN);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnKlienActionPerformed

    private void btnHpsKlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsKlienActionPerformed
        try {
            mycode.hapusKlien(txtIdKlien.getText());
            mycode.tampilDataKlien(tabelKlien, "SELECT*FROM klien");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsKlienActionPerformed

    private void txtNamaKlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaKlienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKlienActionPerformed

    private void txtNamaPengacaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPengacaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPengacaraActionPerformed

    private void btnHpsPengacaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsPengacaraActionPerformed
        try {
            mycode.hapusPengacara(txtIdPengacara.getText());
            mycode.tampilDataPengacara(tabelPengacara, "SELECT*FROM pengacara");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsPengacaraActionPerformed

    private void btnSmpnPengacaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnPengacaraActionPerformed
        try {
            if(txtIdPengacara.getText().isEmpty()){ // Asumsi nama: txtIdPengacara
                JOptionPane.showMessageDialog(null, "ID Belum Diisi");
                txtIdPengacara.requestFocus();
            } else if(txtNamaPengacara.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Pengacara Belum Diisi");
                txtNamaPengacara.requestFocus();
            } else if(txtAlamatPengacara.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "Alamat Belum Diisi");
                txtAlamatPengacara.requestFocus();
            } else if(txtTeleponPengacara.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "Telepon Belum Diisi");
                txtTeleponPengacara.requestFocus();
            } else if(txtInstansi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Instansi Belum Diisi");
                txtInstansi.requestFocus();
            } else {
                mycode.simpanPengacara02(txtIdPengacara.getText(), txtNamaPengacara.getText(),
                                         txtAlamatPengacara.getText(), txtTeleponPengacara.getText(),
                                         txtInstansi.getText());

                // Refresh tabel
                mycode.tampilDataPengacara(tabelPengacara, "SELECT*FROM pengacara");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtNamaPengacara.setText(mycode.CEK_NAMA_PENGACARA);
                    txtAlamatPengacara.setText(mycode.CEK_ALAMAT_PENGACARA);
                    txtTeleponPengacara.setText(mycode.CEK_TELEPON_PENGACARA);
                    txtInstansi.setText(mycode.CEK_INSTANSI);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnPengacaraActionPerformed

    private void btnUbhPengacaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhPengacaraActionPerformed
        try {
            mycode.ubahPengacara(txtIdPengacara.getText(), txtNamaPengacara.getText(),
                                 txtAlamatPengacara.getText(), txtTeleponPengacara.getText(),
                                 txtInstansi.getText());

            mycode.tampilDataPengacara(tabelPengacara, "SELECT*FROM pengacara");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhPengacaraActionPerformed

    private void txtCariPengacaraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPengacaraKeyReleased
        String c = txtCariPengacara.getText();
        String cari = "SELECT*FROM pengacara WHERE id LIKE '%"+c+"%'"+
                      "OR nama_pengacara LIKE '%"+c+"%' OR alamat LIKE '%"+c+"%'"+
                      "OR telepon LIKE '%"+c+"%' OR instansi LIKE '%"+c+"%'";
        mycode.tampilDataPengacara(tabelPengacara, cari);
    }//GEN-LAST:event_txtCariPengacaraKeyReleased

    private void txtIdPengacaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPengacaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPengacaraActionPerformed

    private void txtNamaPerkaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPerkaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPerkaraActionPerformed

    private void btnHpsKatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsKatActionPerformed
        try {
                mycode.hapusKategoriPerkara(txtIdKategori.getText());
                mycode.tampilDataKategoriPerkara(tabelKategoriPerkara, "SELECT*FROM kategori_perkara");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsKatActionPerformed

    private void btnSmpnKatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnKatActionPerformed
        try {
            if(txtIdKategori.getText().isEmpty()){ // Asumsi nama: txtIdKategori
                JOptionPane.showMessageDialog(null, "ID Belum Diisi");
                txtIdKategori.requestFocus();
            } else if(txtNamaPerkara.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Perkara Belum Diisi");
                txtNamaPerkara.requestFocus();
            } else if(txtJenisPerkara_Kat.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "Jenis Perkara Belum Diisi");
                txtJenisPerkara_Kat.requestFocus();
            } else if(txtDeskripsiPerkara.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Deskripsi Belum Diisi");
                txtDeskripsiPerkara.requestFocus();
            } else {
                mycode.simpanKategoriPerkara02(txtIdKategori.getText(), txtNamaPerkara.getText(),
                                               txtJenisPerkara_Kat.getText(), txtDeskripsiPerkara.getText());

                // Refresh tabel
                mycode.tampilDataKategoriPerkara(tabelKategoriPerkara, "SELECT*FROM kategori_perkara");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtNamaPerkara.setText(mycode.CEK_NAMA_PERKARA);
                    txtJenisPerkara_Kat.setText(mycode.CEK_JENIS_PERKARA_KAT);
                    txtDeskripsiPerkara.setText(mycode.CEK_DESKRIPSI_PERKARA);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnKatActionPerformed

    private void btnUbhKatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhKatActionPerformed
        try {
            mycode.ubahKategoriPerkara(txtIdKategori.getText(), txtNamaPerkara.getText(),
                                       txtJenisPerkara_Kat.getText(), txtDeskripsiPerkara.getText());

            // Refresh tabel
            mycode.tampilDataKategoriPerkara(tabelKategoriPerkara, "SELECT*FROM kategori_perkara");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhKatActionPerformed

    private void txtCariKategoriPerkaraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKategoriPerkaraKeyReleased
        String c = txtCariKategoriPerkara.getText();
        String cari = "SELECT*FROM kategori_perkara WHERE id LIKE '%"+c+"%'"+
                      "OR nama_perkara LIKE '%"+c+"%' OR jenis_perkara LIKE '%"+c+"%'";
        mycode.tampilDataKategoriPerkara(tabelKategoriPerkara, cari);
    }//GEN-LAST:event_txtCariKategoriPerkaraKeyReleased

    private void txtIdKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKategoriActionPerformed

    private void btnHpsPerkaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsPerkaraActionPerformed
        try {
            mycode.hapusPerkara(txtIdPerkara.getText());
            mycode.tampilDataPerkara(tabelPerkara, "SELECT*FROM perkara");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsPerkaraActionPerformed

    private void btnSmpnPerkaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnPerkaraActionPerformed
        try {
            if(txtIdPerkara.getText().isEmpty()){ // Asumsi nama: txtIdPerkara
                JOptionPane.showMessageDialog(null, "ID Belum Diisi");
                txtIdPerkara.requestFocus();
            } else if(txtJenisPerkara_Per.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "Jenis Perkara Belum Diisi");
                txtJenisPerkara_Per.requestFocus();
            } else if(txtNoPerkara.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No Perkara Belum Diisi");
                txtNoPerkara.requestFocus();
            } else if(txtKategoriId.getText().isEmpty()){ // Asumsi FK
                JOptionPane.showMessageDialog(null, "ID Kategori Belum Diisi");
                txtKategoriId.requestFocus();
            } else if(txtTglMulai.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tgl Mulai Belum Diisi");
                txtTglMulai.requestFocus();
            } else if(txtTglSelesai.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tgl Selesai Belum Diisi");
                txtTglSelesai.requestFocus();
            } else if(txtStatusPerkara.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "Status Belum Diisi");
                txtStatusPerkara.requestFocus();
            } else if(txtKlienId.getText().isEmpty()){ // Asumsi FK
                JOptionPane.showMessageDialog(null, "ID Klien Belum Diisi");
                txtKlienId.requestFocus();
            } else if(txtNamaTerdakwa.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Terdakwa Belum Diisi");
                txtNamaTerdakwa.requestFocus();
            } else if(txtPengacaraId.getText().isEmpty()){ // Asumsi FK
                JOptionPane.showMessageDialog(null, "ID Pengacara Belum Diisi");
                txtPengacaraId.requestFocus();
            } else if(txtKeteranganPerkara.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "Keterangan Belum Diisi");
                txtKeteranganPerkara.requestFocus();
            } else if(txtDokumen.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Dokumen Belum Diisi");
                txtDokumen.requestFocus();
            } else if(txtSuratKuasa.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Surat Kuasa Belum Diisi");
                txtSuratKuasa.requestFocus();
            } else {
                mycode.simpanPerkara02(txtIdPerkara.getText(), txtJenisPerkara_Per.getText(),
                                       txtNoPerkara.getText(), txtKategoriId.getText(),
                                       txtTglMulai.getText(), txtTglSelesai.getText(),
                                       txtStatusPerkara.getText(), txtKlienId.getText(),
                                       txtNamaTerdakwa.getText(), txtPengacaraId.getText(),
                                       txtKeteranganPerkara.getText(), txtDokumen.getText(),
                                       txtSuratKuasa.getText());

                // Refresh tabel
                mycode.tampilDataPerkara(tabelPerkara, "SELECT*FROM perkara");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtJenisPerkara_Per.setText(mycode.CEK_JENIS_PERKARA);
                    txtNoPerkara.setText(mycode.CEK_NO_PERKARA);
                    txtKategoriId.setText(mycode.CEK_KATEGORI_ID);
                    txtTglMulai.setText(mycode.CEK_TGL_MULAI);
                    txtTglSelesai.setText(mycode.CEK_TGL_SELESAI);
                    txtStatusPerkara.setText(mycode.CEK_STATUS_PERKARA);
                    txtKlienId.setText(mycode.CEK_KLIEN_ID);
                    txtNamaTerdakwa.setText(mycode.CEK_NAMA_TERDAKWA);
                    txtPengacaraId.setText(mycode.CEK_PENGACARA_ID);
                    txtKeteranganPerkara.setText(mycode.CEK_KETERANGAN);
                    txtDokumen.setText(mycode.CEK_DOKUMEN);
                    txtSuratKuasa.setText(mycode.CEK_SURAT_KUASA);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnPerkaraActionPerformed

    private void btnUbhPerkaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhPerkaraActionPerformed
        try {
            mycode.ubahPerkara(txtIdPerkara.getText(), txtJenisPerkara_Per.getText(),
                               txtNoPerkara.getText(), txtKategoriId.getText(),
                               txtTglMulai.getText(), txtTglSelesai.getText(),
                               txtStatusPerkara.getText(), txtKlienId.getText(),
                               txtNamaTerdakwa.getText(), txtPengacaraId.getText(),
                               txtKeteranganPerkara.getText(), txtDokumen.getText(),
                               txtSuratKuasa.getText());

            // Refresh tabel
            mycode.tampilDataPerkara(tabelPerkara, "SELECT*FROM perkara");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhPerkaraActionPerformed

    private void txtCariPerkaraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPerkaraKeyReleased
        String c = txtCariPerkara.getText();
        String cari = "SELECT*FROM perkara WHERE id LIKE '%"+c+"%'"+
                      "OR jenis_perkara LIKE '%"+c+"%' OR no_perkara LIKE '%"+c+"%'"+
                      "OR kategori_perkara_id_kategori LIKE '%"+c+"%' OR status LIKE '%"+c+"%'"+
                      "OR klien_id_klien LIKE '%"+c+"%' OR nama_terdakwa LIKE '%"+c+"%'"+
                      "OR pengacara_id_pengacara LIKE '%"+c+"%'";
        mycode.tampilDataPerkara(tabelPerkara, cari);
    }//GEN-LAST:event_txtCariPerkaraKeyReleased

    private void tabelKlienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKlienMouseClicked
        int baris = tabelKlien.getSelectedRow();
        txtIdKlien.setText(tabelKlien.getValueAt(baris, 0).toString());
        txtNamaKlien.setText(tabelKlien.getValueAt(baris, 1).toString());
        txtTempatLahir.setText(tabelKlien.getValueAt(baris, 2).toString());
        txtTanggalLahir.setText(tabelKlien.getValueAt(baris, 3).toString());
        txtKtp.setText(tabelKlien.getValueAt(baris, 4).toString());
        txtJenisKelamin.setText(tabelKlien.getValueAt(baris, 5).toString());
        txtPekerjaan.setText(tabelKlien.getValueAt(baris, 6).toString());
        txtAlamatKlien.setText(tabelKlien.getValueAt(baris, 7).toString());
        txtTeleponKlien.setText(tabelKlien.getValueAt(baris, 8).toString());
        txtEmailKlien.setText(tabelKlien.getValueAt(baris, 9).toString());
    }//GEN-LAST:event_tabelKlienMouseClicked

    private void btnCetakKlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakKlienActionPerformed
        mycode.cetaklaporan("src/report/klien.jrxml", "SELECT * FROM klien"); 
    }//GEN-LAST:event_btnCetakKlienActionPerformed

    private void btnCetakPengacaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakPengacaraActionPerformed
        mycode.cetaklaporan("src/report/pengacara.jrxml", "SELECT * FROM pengacara"); 
    }//GEN-LAST:event_btnCetakPengacaraActionPerformed

    private void btnCetakKatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakKatActionPerformed
        mycode.cetaklaporan("src/report/kategori_perkara.jrxml", "SELECT * FROM kategori_perkara"); 
    }//GEN-LAST:event_btnCetakKatActionPerformed

    private void btnCetakPerkaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakPerkaraActionPerformed
        mycode.cetaklaporan("src/report/perkara.jrxml", "SELECT * FROM perkara"); 
    }//GEN-LAST:event_btnCetakPerkaraActionPerformed

    private void tabelPengacaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPengacaraMouseClicked
        int baris = tabelPengacara.getSelectedRow();
        txtIdPengacara.setText(tabelPengacara.getValueAt(baris, 0).toString());
        txtNamaPengacara.setText(tabelPengacara.getValueAt(baris, 1).toString());
        txtAlamatPengacara.setText(tabelPengacara.getValueAt(baris, 2).toString());
        txtTeleponPengacara.setText(tabelPengacara.getValueAt(baris, 3).toString());
        txtInstansi.setText(tabelPengacara.getValueAt(baris, 4).toString());
    }//GEN-LAST:event_tabelPengacaraMouseClicked

    private void tabelKategoriPerkaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKategoriPerkaraMouseClicked
        int baris = tabelKategoriPerkara.getSelectedRow();
        txtIdKategori.setText(tabelKategoriPerkara.getValueAt(baris, 0).toString());
        txtNamaPerkara.setText(tabelKategoriPerkara.getValueAt(baris, 1).toString());
        txtJenisPerkara_Kat.setText(tabelKategoriPerkara.getValueAt(baris, 2).toString());
        txtDeskripsiPerkara.setText(tabelKategoriPerkara.getValueAt(baris, 3).toString());
    }//GEN-LAST:event_tabelKategoriPerkaraMouseClicked

    private void tabelPerkaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPerkaraMouseClicked
        int baris = tabelPerkara.getSelectedRow();
        txtIdPerkara.setText(tabelPerkara.getValueAt(baris, 0).toString());
        txtJenisPerkara_Per.setText(tabelPerkara.getValueAt(baris, 1).toString());
        txtNoPerkara.setText(tabelPerkara.getValueAt(baris, 2).toString());
        txtKategoriId.setText(tabelPerkara.getValueAt(baris, 3).toString());
        txtTglMulai.setText(tabelPerkara.getValueAt(baris, 4).toString());
        txtTglSelesai.setText(tabelPerkara.getValueAt(baris, 5).toString());
        txtStatusPerkara.setText(tabelPerkara.getValueAt(baris, 6).toString());
        txtKlienId.setText(tabelPerkara.getValueAt(baris, 7).toString());
        txtNamaTerdakwa.setText(tabelPerkara.getValueAt(baris, 8).toString());
        txtPengacaraId.setText(tabelPerkara.getValueAt(baris, 9).toString());
        txtKeteranganPerkara.setText(tabelPerkara.getValueAt(baris, 10).toString());
        txtDokumen.setText(tabelPerkara.getValueAt(baris, 11).toString());
        txtSuratKuasa.setText(tabelPerkara.getValueAt(baris, 12).toString());
    }//GEN-LAST:event_tabelPerkaraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnCetakKat;
    private javax.swing.JButton btnCetakKlien;
    private javax.swing.JButton btnCetakPengacara;
    private javax.swing.JButton btnCetakPerkara;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHpsKat;
    private javax.swing.JButton btnHpsKlien;
    private javax.swing.JButton btnHpsPengacara;
    private javax.swing.JButton btnHpsPerkara;
    private javax.swing.JButton btnKategoriPerkara;
    private javax.swing.JButton btnKlien;
    private javax.swing.JButton btnPengacara;
    private javax.swing.JButton btnPerkara;
    private javax.swing.JButton btnSmpnKat;
    private javax.swing.JButton btnSmpnKlien;
    private javax.swing.JButton btnSmpnPengacara;
    private javax.swing.JButton btnSmpnPerkara;
    private javax.swing.JButton btnUbhKat;
    private javax.swing.JButton btnUbhKlien;
    private javax.swing.JButton btnUbhPengacara;
    private javax.swing.JButton btnUbhPerkara;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlKategoriPerkara;
    private javax.swing.JPanel pnlKlien;
    private javax.swing.JPanel pnlPengacara;
    private javax.swing.JPanel pnlPerkara;
    private javax.swing.JTable tabelKategoriPerkara;
    private javax.swing.JTable tabelKlien;
    private javax.swing.JTable tabelPengacara;
    private javax.swing.JTable tabelPerkara;
    private javax.swing.JTextField txtAlamatKlien;
    private javax.swing.JTextField txtAlamatPengacara;
    private javax.swing.JTextField txtCariKategoriPerkara;
    private javax.swing.JTextField txtCariKlien;
    private javax.swing.JTextField txtCariPengacara;
    private javax.swing.JTextField txtCariPerkara;
    private javax.swing.JTextField txtDeskripsiPerkara;
    private javax.swing.JTextField txtDokumen;
    private javax.swing.JTextField txtEmailKlien;
    private javax.swing.JTextField txtIdKategori;
    private javax.swing.JTextField txtIdKlien;
    private javax.swing.JTextField txtIdPengacara;
    private javax.swing.JTextField txtIdPerkara;
    private javax.swing.JTextField txtInstansi;
    private javax.swing.JTextField txtJenisKelamin;
    private javax.swing.JTextField txtJenisPerkara_Kat;
    private javax.swing.JTextField txtJenisPerkara_Per;
    private javax.swing.JTextField txtKategoriId;
    private javax.swing.JTextField txtKeteranganPerkara;
    private javax.swing.JTextField txtKlienId;
    private javax.swing.JTextField txtKtp;
    private javax.swing.JTextField txtNamaKlien;
    private javax.swing.JTextField txtNamaPengacara;
    private javax.swing.JTextField txtNamaPerkara;
    private javax.swing.JTextField txtNamaTerdakwa;
    private javax.swing.JTextField txtNoPerkara;
    private javax.swing.JTextField txtPekerjaan;
    private javax.swing.JTextField txtPengacaraId;
    private javax.swing.JTextField txtStatusPerkara;
    private javax.swing.JTextField txtSuratKuasa;
    private javax.swing.JTextField txtTanggalLahir;
    private javax.swing.JTextField txtTeleponKlien;
    private javax.swing.JTextField txtTeleponPengacara;
    private javax.swing.JTextField txtTempatLahir;
    private javax.swing.JTextField txtTglMulai;
    private javax.swing.JTextField txtTglSelesai;
    // End of variables declaration//GEN-END:variables
}
